// Bundles brand icon paths from the `simple-icons` package for the slugs used in shared/catalog.ts.
// Missing slugs are reported; the UI falls back to a favicon lookup, then a monogram tile.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as simpleIcons from "simple-icons";
import * as legacyIcons from "simple-icons-legacy";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const catalogSrc = fs.readFileSync(path.join(root, "shared/catalog.ts"), "utf8");

// Parse t("id","Name","cat","url","desc"[, "iconSlug"]) calls.
const callRe = /\bt\(\s*"([^"]+)"\s*,\s*"[^"]*"\s*,\s*"[^"]*"\s*,\s*"[^"]*"\s*,\s*"(?:[^"\\]|\\.)*"\s*(?:,\s*"([^"]+)")?\s*\)/g;
const slugs = new Set();
for (const m of catalogSrc.matchAll(callRe)) slugs.add(m[2] ?? m[1]);

// Current release wins; the older release fills brands that were later removed upstream.
const bySlug = new Map();
for (const pkg of [legacyIcons, simpleIcons]) {
  for (const value of Object.values(pkg)) {
    if (value && typeof value === "object" && "slug" in value) bySlug.set(value.slug, value);
  }
}

const found = {};
const missing = [];
for (const slug of [...slugs].sort()) {
  const icon = bySlug.get(slug);
  if (icon) found[slug] = { path: icon.path, hex: icon.hex };
  else missing.push(slug);
}

const out =
  "// Generated by scripts/gen-icons.mjs - do not edit.\n" +
  "export const ICONS: Record<string, { path: string; hex: string }> = " +
  JSON.stringify(found, null, 2) +
  ";\n";
fs.mkdirSync(path.join(root, "src/data"), { recursive: true });
fs.writeFileSync(path.join(root, "src/data/icons.generated.ts"), out);

console.log(`icons: ${Object.keys(found).length} bundled, ${missing.length} missing (favicon fallback)`);
if (missing.length) console.log("missing:", missing.join(", "));
